name: Continuous Integration

on:
  push:
    branches: [ master ]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install
        run: yarn --no-progress --non-interactive --no-lockfile

      - name: Lint code
        run: yarn lint

      - name: Test
        run: yarn test --colors --coverage

      - name: Build
        run: yarn build

      - name: Export storybook
        run: yarn storybook:export
